/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package usafacts.galactic.spending.app

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import usafacts.galactic.spending.app.commands.CreateDatasetsCommand
import usafacts.galactic.spending.app.commands.ImportDataCommand
import usafacts.galactic.spending.app.commands.RunCommand

class AppMainCommand : CliktCommand() {
    init {
        subcommands(
            RunCommand(),
            ImportDataCommand(),
            CreateDatasetsCommand()
        )
    }

    override fun run() {
    }
}

fun main(vararg args: String) {
    AppMainCommand().main(args)
}
