/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package usafacts.galactic.spending.app

import usafacts.galactic.spending.app.commands.MainCommand

fun main(vararg args: String) {
    MainCommand().main(args)
}
