/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("usafacts.galactic.spending.kotlin-application-conventions")
    id("org.jetbrains.kotlin.plugin.spring") version "1.9.20"
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:3.2.0")
    implementation("com.github.ajalt.clikt:clikt:4.2.1")
}

application {
    // Define the main class for the application.
    mainClass.set("usafacts.galactic.spending.app.AppKt")
}
