/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("usafacts.galactic.spending.kotlin-application-conventions")
}

dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("usafacts.galactic.spending.app.AppKt")
}
